export type BlogCategory =
  | "WiFi & Internet"
  | "Rumah Digital"
  | "Teknologi"
  | "Tips Hemat"
  | "Adab"
  | "Sosial"
  | "Ibadah"
  | "Umum";

export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  category: BlogCategory;
  date: string;
  readTime: string;
  cover: string;
  coverAlt: string;
  content: string[];
};

export const blogPosts: BlogPost[] = [
  {
    slug: "tips-memilih-paket-wifi-rumah",
    title: "Tips Memilih Paket WiFi Rumah yang Tepat",
    excerpt: "Cara memilih kecepatan internet sesuai kebutuhan keluarga.",
    category: "WiFi & Internet",
    date: "2026-09-10",
    readTime: "9 menit",
    cover: "/blog/blog-man-phone.jpg",
    coverAlt: "Pria memakai smartphone",
    content: [
      "Memilih paket WiFi sering membuat bingung karena banyak angka Mbps dan istilah teknis. Padahal intinya sederhana: sesuaikan kapasitas dengan kebiasaan online keluarga, bukan dengan rasa 'takut kehabisan kecepatan'.",
      'Mulai dari hitung perangkat yang biasa aktif bersamaan. Smartphone, laptop, TV pintar, CCTV, dan konsol game bisa online di waktu yang sama. Semakin banyak perangkat, semakin besar kebutuhan bandwidth agar semuanya tetap nyaman.',
      'Untuk rumah kecil dengan 1–5 perangkat, paket 15 Mbps biasanya cukup untuk browsing, chat, media sosial, dan streaming standar. Jika sering meeting online atau menonton di beberapa layar, 30–50 Mbps terasa lebih longgar.',
      'Rumah sibuk dengan banyak anggota dan perangkat sebaiknya mempertimbangkan 75–100 Mbps. Lebih hemat ambil yang pas sejak awal daripada sering frustasi lalu ganti-ganti paket.',
      'Selain angka kecepatan, pastikan paket unlimited tanpa FUP yang membingungkan, harga flat tiap bulan, dan biaya instalasi dijelaskan di awal. Fiber optic umumnya lebih tahan cuaca dibanding radio jarak jauh.',
      'Sebelum daftar, cek coverage kampung Anda dan tanyakan jadwal instalasi. Di SaGa-Net, konsultasi via WhatsApp membantu menyesuaikan paket dengan kondisi rumah secara lebih realistis.',
      'Uji pola pemakaian seminggu: kapan jam tersibuk, aktivitas apa yang paling sering, dan apakah sering upload file besar. Data sederhana ini membuat keputusan lebih tepat.',
      'Kesimpulan: paket terbaik bukan yang paling mahal, melainkan yang cukup, stabil, transparan, dan mudah mendapat bantuan saat ada gangguan.',
    ],
  },
  {
    slug: "internet-unlimited-benar-benar-tanpa-batas",
    title: "Internet Unlimited: Benarkah Tanpa Batas?",
    excerpt: "Memahami unlimited, FUP, dan pertanyaan sebelum berlangganan.",
    category: "WiFi & Internet",
    date: "2026-09-09",
    readTime: "7 menit",
    cover: "/blog/blog-man-work.jpg",
    coverAlt: "Pria bekerja dengan laptop",
    content: [
      "Memahami unlimited, FUP, dan pertanyaan sebelum berlangganan. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "wifi-untuk-keluarga-besar",
    title: "WiFi untuk Keluarga Besar: Berapa Mbps yang Cocok?",
    excerpt: "Menyesuaikan kecepatan dengan banyak perangkat di rumah.",
    category: "WiFi & Internet",
    date: "2026-09-08",
    readTime: "7 menit",
    cover: "/blog/blog-family.jpg",
    coverAlt: "Ayah dan anak belajar bersama",
    content: [
      "Menyesuaikan kecepatan dengan banyak perangkat di rumah. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "tanda-sudah-saatnya-naik-paket",
    title: "Tanda Sudah Saatnya Naik Paket Internet",
    excerpt: "Sinyal bahwa kapasitas paket sudah tidak mencukupi.",
    category: "WiFi & Internet",
    date: "2026-09-07",
    readTime: "7 menit",
    cover: "/blog/blog-kids.jpg",
    coverAlt: "Anak-anak belajar bersama",
    content: [
      "Sinyal bahwa kapasitas paket sudah tidak mencukupi. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "internet-untuk-usaha-kecil-di-rumah",
    title: "Internet untuk Usaha Kecil di Rumah",
    excerpt: "Kebutuhan koneksi untuk order, chat, dan live selling.",
    category: "WiFi & Internet",
    date: "2026-09-06",
    readTime: "9 menit",
    cover: "/blog/blog-elder.jpg",
    coverAlt: "Orang tua di rumah",
    content: [
      'Usaha kecil di rumah bergantung pada koneksi yang bisa diandalkan: cek order, balas chat pelanggan, upload produk, sampai live selling. Jika internet sering putus, peluang hilang begitu saja.',
      'Untuk usaha ringan, paket menengah sering sudah cukup. Namun jika ada live streaming, banyak foto produk berukuran besar, atau beberapa admin online bersamaan, naikkan kapasitasnya.',
      'Pisahkan perangkat kerja dari hiburan bila memungkinkan. Hindari update game besar saat jam operasional toko online.',
      'Keamanan juga penting. Gunakan password kuat dan jangan bagikan WiFi usaha terlalu bebas. Data pelanggan dan transaksi perlu dilindungi.',
      'Siapkan kontak support provider yang mudah dihubungi. Gangguan sebentar saja bisa berdampak ke penjualan harian.',
      'Rapihkan alur kerja digital: folder produk, template balasan chat, dan jadwal upload konten agar koneksi dipakai lebih efisien.',
      'Uji kecepatan di jam sibuk penjualan agar Anda tahu kapasitas nyata, bukan hanya hasil tes pagi hari.',
      'Internet yang tepat membantu usaha rumahan lebih profesional: respons cepat, konten lancar, dan operasional lebih tenang.',
    ],
  },
  {
    slug: "cara-cek-coverage-sebelum-daftar",
    title: "Cara Cek Coverage sebelum Daftar Internet",
    excerpt: "Pastikan alamat sudah terjangkau sebelum berlangganan.",
    category: "WiFi & Internet",
    date: "2026-09-05",
    readTime: "7 menit",
    cover: "/blog/blog-elder-child.jpg",
    coverAlt: "Kakek dan cucu bersama",
    content: [
      "Pastikan alamat sudah terjangkau sebelum berlangganan. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "kenapa-fiber-optic-lebih-stabil",
    title: "Kenapa Fiber Optic Lebih Stabil untuk Rumah?",
    excerpt: "Keunggulan fiber optic dibanding koneksi yang mudah terdampak cuaca.",
    category: "WiFi & Internet",
    date: "2026-09-04",
    readTime: "7 menit",
    cover: "/blog/blog-social.jpg",
    coverAlt: "Percakapan hangat di rumah",
    content: [
      "Keunggulan fiber optic dibanding koneksi yang mudah terdampak cuaca. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "cara-bagi-bandwidth-di-rumah",
    title: "Cara Membagi Bandwidth di Rumah secara Adil",
    excerpt: "Agar semua anggota keluarga tetap nyaman online.",
    category: "WiFi & Internet",
    date: "2026-09-03",
    readTime: "7 menit",
    cover: "/blog/blog-ibadah.jpg",
    coverAlt: "Suasana sudut ibadah di rumah",
    content: [
      "Agar semua anggota keluarga tetap nyaman online. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "wifi-untuk-cctv-rumah",
    title: "WiFi untuk CCTV Rumah: Apa yang Perlu Diperhatikan?",
    excerpt: "Tips agar kamera rumah tidak mengganggu aktivitas online lain.",
    category: "WiFi & Internet",
    date: "2026-09-02",
    readTime: "7 menit",
    cover: "/products/hero-impress.jpg",
    coverAlt: "Ilustrasi jaringan fiber optic",
    content: [
      "Tips agar kamera rumah tidak mengganggu aktivitas online lain. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "memilih-paket-untuk-kos-dan-kontrakan",
    title: "Memilih Paket Internet untuk Kos dan Kontrakan",
    excerpt: "Pertimbangan praktis untuk hunian sewa.",
    category: "WiFi & Internet",
    date: "2026-09-01",
    readTime: "7 menit",
    cover: "/products/plan-15.jpg",
    coverAlt: "Ilustrasi paket internet rumah",
    content: [
      "Pertimbangan praktis untuk hunian sewa. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "wifi-stabil-untuk-belajar-dan-kerja-dari-rumah",
    title: "WiFi Stabil untuk Belajar dan Kerja dari Rumah",
    excerpt: "Koneksi tenang untuk meeting dan kelas daring.",
    category: "Rumah Digital",
    date: "2026-08-31",
    readTime: "9 menit",
    cover: "/products/plan-30.jpg",
    coverAlt: "Ilustrasi aktivitas online rumah",
    content: [
      'Belajar dan kerja dari rumah menuntut koneksi yang konsisten sepanjang hari. Kecepatan tinggi tidak banyak artinya jika sering putus saat video call atau gagal mengunggah tugas.',
      'Fokus pada kestabilan dan kualitas upload. Meeting online, berbagi layar, serta pengumpulan tugas membutuhkan jalur yang tidak mudah naik-turun.',
      'Fiber optic biasanya lebih nyaman untuk kebutuhan ini karena lebih tahan gangguan cuaca dan mendukung koneksi yang lebih seimbang antara unduh dan unggah.',
      'Atur kebiasaan rumah saat jam produktif: tunda update game, unduhan film besar, atau sync cloud yang berat. Prioritaskan perangkat utama agar bandwidth tidak terbagi sia-sia.',
      'Letakkan router di area terbuka, setinggi dada, jauh dari dinding tebal dan benda logam. Sinyal yang merata sering lebih berdampak daripada sekadar naik paket.',
      'Jika banyak orang online bersamaan setiap malam, pertimbangkan naik kapasitas. Lebih tenang membayar sedikit lebih untuk kenyamanan daripada kehilangan fokus kerja atau belajar.',
      'Siapkan juga rencana cadangan sederhana, misalnya hotspot darurat untuk rapat penting, sambil tetap mengandalkan WiFi rumah sebagai jalur utama.',
      'Dengan koneksi yang stabil, rumah menjadi ruang produktif yang lebih tenang—fokus kembali ke pekerjaan dan belajar, bukan ke masalah jaringan.',
    ],
  },
  {
    slug: "checklist-sebelum-pasang-wifi",
    title: "Checklist Sebelum Pasang WiFi di Rumah",
    excerpt: "Persiapan agar instalasi lebih cepat dan rapi.",
    category: "Rumah Digital",
    date: "2026-08-30",
    readTime: "7 menit",
    cover: "/products/plan-50.jpg",
    coverAlt: "Ilustrasi koneksi multi perangkat",
    content: [
      "Persiapan agar instalasi lebih cepat dan rapi. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "keamanan-wifi-rumah-yang-sering-dilupakan",
    title: "Keamanan WiFi Rumah yang Sering Dilupakan",
    excerpt: "Lindungi jaringan rumah dari akses tidak diinginkan.",
    category: "Rumah Digital",
    date: "2026-08-29",
    readTime: "9 menit",
    cover: "/products/plan-voucher.jpg",
    coverAlt: "Ilustrasi voucher internet",
    content: [
      'WiFi rumah menyimpan banyak aktivitas pribadi: chat, transfer bank, kerja, sampai kamera CCTV. Karena itu keamanan dasar perlu dijaga.',
      'Ganti password default router segera setelah instalasi. Gunakan kombinasi yang tidak mudah ditebak dan jangan membagikannya terlalu luas.',
      'Aktifkan enkripsi modern (WPA2/WPA3 bila tersedia). Hindari jaringan terbuka tanpa kata sandi, terutama di lingkungan padat.',
      'Berikan jaringan tamu jika ada fiturnya, agar perangkat tamu tidak langsung masuk ke jaringan utama.',
      'Perbarui firmware router bila memungkinkan, dan matikan fitur jarak jauh yang tidak Anda pakai.',
      'Waspadai perangkat tidak dikenal yang terhubung. Cabut akses jika mencurigakan.',
      'Ajarkan anggota keluarga untuk tidak membagikan password di tempat umum atau ke orang yang tidak perlu.',
      'Keamanan WiFi bukan soal rumit. Kebiasaan kecil ini sudah cukup membantu menjaga rumah digital lebih aman sehari-hari.',
    ],
  },
  {
    slug: "streaming-lancar-di-jam-sibuk",
    title: "Streaming Lancar di Jam Sibuk",
    excerpt: "Agar nonton malam hari tidak sering loading.",
    category: "Rumah Digital",
    date: "2026-08-28",
    readTime: "7 menit",
    cover: "/blog/blog-man-phone.jpg",
    coverAlt: "Pria memakai smartphone",
    content: [
      "Agar nonton malam hari tidak sering loading. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Dalam tema rumah digital, banyak orang mengalami kendala karena kurang perencanaan. Dengan langkah bertahap, hasilnya biasanya lebih terasa.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "anak-dan-internet-sehat-di-rumah",
    title: "Anak dan Internet Sehat di Rumah",
    excerpt: "Dampingi anak online dengan batasan sehat.",
    category: "Rumah Digital",
    date: "2026-08-27",
    readTime: "9 menit",
    cover: "/blog/blog-man-work.jpg",
    coverAlt: "Pria bekerja dengan laptop",
    content: [
      'Internet bermanfaat untuk belajar, berkomunikasi, dan eksplorasi minat anak. Namun tanpa dampingan, waktu layar bisa mudah berlebihan.',
      'Buat kesepakatan sederhana di rumah: jam belajar, jam bermain, dan waktu bebas perangkat. Libatkan anak agar aturan terasa adil, bukan hukuman.',
      'Letakkan perangkat di ruang keluarga saat dipakai malam hari. Ini membantu orang tua tetap bisa menemani dan berdiskusi bila ada konten yang membingungkan.',
      'Ajarkan anak membedakan informasi yang berguna dan yang hanya menghabiskan waktu. Ajak mereka mencari materi belajar atau konten edukatif.',
      'Gunakan internet yang stabil agar kelas daring dan tugas online tidak membuat anak stres. Koneksi buruk sering memicu frustrasi yang tidak perlu.',
      'Dampingi tanpa mengontrol berlebihan. Beri ruang eksplorasi yang aman, lalu evaluasi bersama secara rutin.',
      'Contohkan kebiasaan baik: orang tua yang juga bisa meletakkan ponsel saat waktu kebersamaan biasanya lebih persuasif.',
      'Internet sehat lahir dari kebiasaan bersama. Dengan dampingan hangat, teknologi menjadi alat tumbuh kembang, bukan pengganggu istirahat.',
    ],
  },
  {
    slug: "menata-sudut-kerja-di-rumah",
    title: "Menata Sudut Kerja di Rumah yang Nyaman",
    excerpt: "Ruang kerja kecil yang mendukung fokus dan kesehatan.",
    category: "Rumah Digital",
    date: "2026-08-26",
    readTime: "7 menit",
    cover: "/blog/blog-family.jpg",
    coverAlt: "Ayah dan anak belajar bersama",
    content: [
      "Ruang kerja kecil yang mendukung fokus dan kesehatan. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Dalam tema rumah digital, banyak orang mengalami kendala karena kurang perencanaan. Dengan langkah bertahap, hasilnya biasanya lebih terasa.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "memahami-ping-dan-latensi",
    title: "Memahami Ping dan Latensi untuk Pemula",
    excerpt: "Kenapa game dan video call bisa lag.",
    category: "Teknologi",
    date: "2026-08-25",
    readTime: "7 menit",
    cover: "/blog/blog-kids.jpg",
    coverAlt: "Anak-anak belajar bersama",
    content: [
      "Kenapa game dan video call bisa lag. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Dalam tema teknologi, banyak orang mengalami kendala karena kurang perencanaan. Dengan langkah bertahap, hasilnya biasanya lebih terasa.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "beda-mbps-dan-pengalaman-nyata",
    title: "Beda Mbps di Brosur dan Pengalaman Nyata",
    excerpt: "Angka kecepatan vs rasa saat dipakai.",
    category: "Teknologi",
    date: "2026-08-24",
    readTime: "7 menit",
    cover: "/blog/blog-elder.jpg",
    coverAlt: "Orang tua di rumah",
    content: [
      "Angka kecepatan vs rasa saat dipakai. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "persiapan-musim-hujan-agar-internet-aman",
    title: "Persiapan Musim Hujan agar Internet Tetap Aman",
    excerpt: "Lindungi perangkat saat cuaca buruk.",
    category: "Teknologi",
    date: "2026-08-23",
    readTime: "7 menit",
    cover: "/blog/blog-elder-child.jpg",
    coverAlt: "Kakek dan cucu bersama",
    content: [
      "Lindungi perangkat saat cuaca buruk. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "belajar-seumur-hidup-di-era-digital",
    title: "Belajar Seumur Hidup di Era Digital",
    excerpt: "Pakai internet untuk menambah keterampilan.",
    category: "Teknologi",
    date: "2026-08-22",
    readTime: "7 menit",
    cover: "/blog/blog-social.jpg",
    coverAlt: "Percakapan hangat di rumah",
    content: [
      "Pakai internet untuk menambah keterampilan. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Dalam tema teknologi, banyak orang mengalami kendala karena kurang perencanaan. Dengan langkah bertahap, hasilnya biasanya lebih terasa.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "melindungi-data-pribadi-di-ponsel",
    title: "Melindungi Data Pribadi di Ponsel",
    excerpt: "Langkah dasar agar informasi tidak mudah bocor.",
    category: "Teknologi",
    date: "2026-08-21",
    readTime: "7 menit",
    cover: "/blog/blog-ibadah.jpg",
    coverAlt: "Suasana sudut ibadah di rumah",
    content: [
      "Langkah dasar agar informasi tidak mudah bocor. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Dalam tema teknologi, banyak orang mengalami kendala karena kurang perencanaan. Dengan langkah bertahap, hasilnya biasanya lebih terasa.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "memilih-perangkat-rumah-tangga-pintar",
    title: "Memilih Perangkat Rumah Pintar dengan Bijak",
    excerpt: "Pertimbangan sebelum menambah perangkat IoT.",
    category: "Teknologi",
    date: "2026-08-20",
    readTime: "7 menit",
    cover: "/products/hero-impress.jpg",
    coverAlt: "Ilustrasi jaringan fiber optic",
    content: [
      "Pertimbangan sebelum menambah perangkat IoT. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Dalam tema teknologi, banyak orang mengalami kendala karena kurang perencanaan. Dengan langkah bertahap, hasilnya biasanya lebih terasa.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "cara-mempercepat-wifi-di-rumah",
    title: "Cara Mempercepat WiFi tanpa Ganti Paket",
    excerpt: "Optimasi sederhana yang sering langsung terasa.",
    category: "Tips Hemat",
    date: "2026-08-19",
    readTime: "7 menit",
    cover: "/products/plan-15.jpg",
    coverAlt: "Ilustrasi paket internet rumah",
    content: [
      "Optimasi sederhana yang sering langsung terasa. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "cara-hemat-biaya-internet-bulanan",
    title: "Cara Hemat Biaya Internet Bulanan",
    excerpt: "Tagihan terkendali tanpa mengorbankan kenyamanan.",
    category: "Tips Hemat",
    date: "2026-08-18",
    readTime: "9 menit",
    cover: "/products/plan-30.jpg",
    coverAlt: "Ilustrasi aktivitas online rumah",
    content: [
      'Hemat biaya internet bukan berarti selalu memilih yang termurah. Paket terlalu rendah justru membuat frustasi dan akhirnya memaksa naik turun paket berkali-kali.',
      'Hitung kebutuhan realistis keluarga. Jika 15 Mbps sudah cukup, tidak perlu memaksa ke 100 Mbps. Sebaliknya, rumah sibuk lebih hemat ambil yang pas sejak awal.',
      'Manfaatkan promo instalasi bila ada, tetapi utamakan biaya bulanan jangka panjang. Yang dibayar tiap bulan lebih menentukan daripada diskon sekali di awal.',
      'Kurangi langganan digital yang jarang dipakai. Internet cepat tetap terasa mahal jika digabung banyak aplikasi berbayar yang tidak aktif.',
      'Atur unduhan besar di luar jam sibuk agar kapasitas paket terasa lebih optimal.',
      'Pantau kebiasaan keluarga secara ringan: matikan perangkat idle dan batasi auto-update di malam hari.',
      'Tanyakan paket yang paling sesuai ke admin berdasarkan jumlah perangkat dan aktivitas utama rumah Anda.',
      'Dengan perencanaan sederhana, Anda bisa mendapat internet nyaman tanpa membuat tagihan membengkak.',
    ],
  },
  {
    slug: "posisi-router-yang-benar",
    title: "Posisi Router yang Benar agar Sinyal Merata",
    excerpt: "Letak router menentukan jangkauan WiFi.",
    category: "Tips Hemat",
    date: "2026-08-17",
    readTime: "7 menit",
    cover: "/products/plan-50.jpg",
    coverAlt: "Ilustrasi koneksi multi perangkat",
    content: [
      "Letak router menentukan jangkauan WiFi. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "router-gratis-sewa-apa-artinya",
    title: "Router Gratis Sewa: Apa Artinya?",
    excerpt: "Manfaat dan ketentuan sewa modem/router.",
    category: "Tips Hemat",
    date: "2026-08-16",
    readTime: "7 menit",
    cover: "/products/plan-voucher.jpg",
    coverAlt: "Ilustrasi voucher internet",
    content: [
      "Manfaat dan ketentuan sewa modem/router. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "kapan-pakai-voucher-dan-paket-bulanan",
    title: "Voucher WiFi atau Paket Bulanan?",
    excerpt: "Pilih sesuai pola pemakaian Anda.",
    category: "Tips Hemat",
    date: "2026-08-15",
    readTime: "7 menit",
    cover: "/blog/blog-man-phone.jpg",
    coverAlt: "Pria memakai smartphone",
    content: [
      "Pilih sesuai pola pemakaian Anda. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Perhatikan jumlah perangkat, jam sibuk, dan kestabilan jaringan sebelum memutuskan. Fiber optic umumnya lebih tahan cuaca dan lebih konsisten.",
      "Uji kecepatan di beberapa waktu berbeda, lalu bandingkan kebutuhan puncak keluarga atau usaha Anda.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "adab-berbicara-dalam-keluarga",
    title: "Adab Berbicara dalam Keluarga",
    excerpt: "Tutur kata yang membuat rumah lebih tenang.",
    category: "Adab",
    date: "2026-08-14",
    readTime: "9 menit",
    cover: "/blog/blog-man-work.jpg",
    coverAlt: "Pria bekerja dengan laptop",
    content: [
      'Adab berbicara adalah fondasi kehangatan rumah. Kata yang lembut bisa menenangkan suasana, sementara kata kasar sering meninggalkan luka meski masalahnya sudah selesai.',
      'Biasakan kebiasaan kecil: menyapa saat pulang, meminta maaf jika salah, dan mengucapkan terima kasih untuk bantuan sehari-hari. Kalimat pendek ini membentuk rasa saling dihargai.',
      'Saat berbeda pendapat, dahulukan mendengar. Biarkan lawan bicara menyelesaikan kalimatnya. Banyak konflik membesar karena saling memotong dan ingin menang sendiri.',
      'Hindari mengangkat suara di depan anak. Anak belajar dari contoh. Jika orang tua terbiasa tenang, anak lebih mudah meniru cara menyelesaikan masalah tanpa marah berlebihan.',
      'Di era chat, adab juga berlaku di layar. Jangan mengirim pesan marah saat emosi memuncak. Tunggu dingin, lalu sampaikan dengan jelas dan sopan.',
      'Pilih waktu bicara yang tepat. Membahas isu penting saat lapar, lelah, atau terburu-buru biasanya hanya memperkeruh suasana.',
      'Jika sudah terlanjur salah bicara, segera perbaiki. Permintaan maaf yang tulus sering lebih memulihkan hubungan daripada pembelaan panjang.',
      'Rumah yang menjaga adab bicara biasanya lebih nyaman ditinggali. Bukan karena tanpa masalah, tapi karena cara menyikapi masalahnya lebih beradab.',
    ],
  },
  {
    slug: "adab-menggunakan-media-sosial",
    title: "Adab Menggunakan Media Sosial",
    excerpt: "Online tetap sopan dan bermanfaat.",
    category: "Adab",
    date: "2026-08-13",
    readTime: "9 menit",
    cover: "/blog/blog-family.jpg",
    coverAlt: "Ayah dan anak belajar bersama",
    content: [
      'Media sosial memudahkan komunikasi, tetapi juga mudah menjadi tempat salah paham. Karena itu, adab digital sama pentingnya dengan adab di dunia nyata.',
      'Sebelum membagikan informasi, pastikan sumbernya jelas. Menyerukan berita yang belum jelas kebenarannya bisa merugikan banyak orang.',
      'Jaga privasi diri dan orang lain. Tidak semua momen keluarga perlu dipublikasikan. Hormati juga jika ada yang tidak ingin fotonya diunggah.',
      'Hindari komentar mengejek, fitnah, atau perdebatan yang hanya ingin menang. Jika tidak memberi manfaat, lebih baik diam atau tinggalkan percakapan.',
      'Atur waktu layar. Media sosial yang berlebihan bisa menggerus waktu ibadah, kerja, belajar, dan kebersamaan keluarga.',
      'Gunakan akun untuk menyebarkan kebaikan: ilmu, inspirasi, dan komunikasi yang membangun.',
      'Jika tersulut emosi, jeda sejenak sebelum membalas. Banyak penyesalan lahir dari komentar yang dikirim terburu-buru.',
      'Teknologi menjadi berkah jika diarahkan dengan adab. Online yang beradab membuat ruang digital lebih sehat untuk semua.',
    ],
  },
  {
    slug: "adab-bertamu-dan-menerima-tamu",
    title: "Adab Bertamu dan Menerima Tamu",
    excerpt: "Sopan santun yang membuat pertemuan nyaman.",
    category: "Adab",
    date: "2026-08-12",
    readTime: "7 menit",
    cover: "/blog/blog-kids.jpg",
    coverAlt: "Anak-anak belajar bersama",
    content: [
      "Sopan santun yang membuat pertemuan nyaman. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Adab yang baik lahir dari kebiasaan: menjaga lisan, menghormati orang lain, dan menahan emosi saat situasi memanas.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "adab-berbeda-pendapat",
    title: "Adab Berbeda Pendapat",
    excerpt: "Menyampaikan pandangan tanpa merusak hubungan.",
    category: "Adab",
    date: "2026-08-11",
    readTime: "7 menit",
    cover: "/blog/blog-elder.jpg",
    coverAlt: "Orang tua di rumah",
    content: [
      "Menyampaikan pandangan tanpa merusak hubungan. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Adab yang baik lahir dari kebiasaan: menjaga lisan, menghormati orang lain, dan menahan emosi saat situasi memanas.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "adab-kepada-orang-tua",
    title: "Adab kepada Orang Tua di Rumah",
    excerpt: "Hormat, sabar, dan peduli kepada orang tua.",
    category: "Adab",
    date: "2026-08-10",
    readTime: "7 menit",
    cover: "/blog/blog-elder-child.jpg",
    coverAlt: "Kakek dan cucu bersama",
    content: [
      "Hormat, sabar, dan peduli kepada orang tua. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Adab yang baik lahir dari kebiasaan: menjaga lisan, menghormati orang lain, dan menahan emosi saat situasi memanas.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "adab-antre-dan-tertib-umum",
    title: "Adab Antre dan Tertib di Tempat Umum",
    excerpt: "Disiplin kecil untuk kenyamanan bersama.",
    category: "Adab",
    date: "2026-08-09",
    readTime: "7 menit",
    cover: "/blog/blog-social.jpg",
    coverAlt: "Percakapan hangat di rumah",
    content: [
      "Disiplin kecil untuk kenyamanan bersama. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Adab yang baik lahir dari kebiasaan: menjaga lisan, menghormati orang lain, dan menahan emosi saat situasi memanas.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "menjaga-kebersihan-hati-dan-perkataan",
    title: "Menjaga Kebersihan Hati dan Perkataan",
    excerpt: "Sikap yang membuat hubungan sosial lebih sehat.",
    category: "Adab",
    date: "2026-08-08",
    readTime: "7 menit",
    cover: "/blog/blog-ibadah.jpg",
    coverAlt: "Suasana sudut ibadah di rumah",
    content: [
      "Sikap yang membuat hubungan sosial lebih sehat. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Adab yang baik lahir dari kebiasaan: menjaga lisan, menghormati orang lain, dan menahan emosi saat situasi memanas.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "menjaga-silaturahmi-di-kampung",
    title: "Menjaga Silaturahmi di Kampung",
    excerpt: "Merawat hubungan tetangga dan kerabat.",
    category: "Sosial",
    date: "2026-08-07",
    readTime: "9 menit",
    cover: "/products/hero-impress.jpg",
    coverAlt: "Ilustrasi jaringan fiber optic",
    content: [
      'Kehidupan kampung terasa hangat ketika tetangga saling kenal dan peduli. Silaturahmi bukan hanya acara besar, melainkan kebiasaan kecil yang dijaga rutin.',
      'Sapa tetangga saat berpapasan, jenguk yang sakit, dan bantu saat ada kerja bakti. Gestur sederhana ini mempererat rasa kebersamaan.',
      'Di era digital, silaturahmi juga bisa dijaga lewat chat singkat atau telepon ke kerabat yang jauh. Yang penting ada kabar dan doa, bukan hanya saat butuh saja.',
      'Hindari ghibah dan prasangka. Banyak hubungan rusak karena cerita yang dibesar-besarkan. Jika ada masalah, selesaikan langsung dengan baik.',
      'Libatkan anak dalam kegiatan sosial agar mereka tumbuh dengan rasa peduli. Anak yang terbiasa berbagi biasanya lebih mudah bergaul dengan sopan.',
      'Gunakan teknologi untuk koordinasi warga, bukan untuk menyebarkan konflik. Grup chat bermanfaat jika diarahkan pada kepentingan bersama.',
      'Luangkan waktu berkunjung meski sebentar. Kehadiran sering lebih berarti daripada hadiah mahal.',
      'Kampung yang kuat sosialnya lebih tahan menghadapi kesulitan, karena tetangga yang dekat sering menjadi penolong pertama.',
    ],
  },
  {
    slug: "gotong-royong-di-era-modern",
    title: "Gotong Royong di Era Modern",
    excerpt: "Kerja sama tetap relevan di zaman digital.",
    category: "Sosial",
    date: "2026-08-06",
    readTime: "9 menit",
    cover: "/products/plan-15.jpg",
    coverAlt: "Ilustrasi paket internet rumah",
    content: [
      'Gotong royong adalah cara masyarakat berbagi beban. Di era modern bentuknya bisa berubah, tetapi semangatnya tetap sama: saling membantu tanpa menunggu imbalan.',
      'Contohnya sederhana: bersama membersihkan saluran air, membantu tetangga yang kesulitan, atau mengorganisir kepanitiaan dengan tertib.',
      'Teknologi bisa mendukung gotong royong. Grup chat warga membantu koordinasi cepat, asal dipakai untuk kepentingan bersama, bukan konflik.',
      'Ajarkan generasi muda bahwa kerja sama lebih kuat daripada ego. Keberhasilan bersama biasanya lebih tahan lama daripada keberhasilan sendirian.',
      'Mulai dari rumah: bagi tugas rumah tangga secara adil. Gotong royong yang sehat lahir dari kebiasaan sehari-hari.',
      'Dokumentasikan kesepakatan warga secara sederhana agar tidak mudah terjadi salah paham.',
      'Hargai kontribusi siapa pun, besar maupun kecil, agar semangat bersama tetap hidup.',
      'Ketika warga terbiasa saling bantu, lingkungan menjadi lebih aman, nyaman, dan penuh kepercayaan.',
    ],
  },
  {
    slug: "mengajarkan-anak-berbagi",
    title: "Mengajarkan Anak Berbagi sejak Dini",
    excerpt: "Menumbuhkan empati lewat kebiasaan kecil.",
    category: "Sosial",
    date: "2026-08-05",
    readTime: "7 menit",
    cover: "/products/plan-30.jpg",
    coverAlt: "Ilustrasi aktivitas online rumah",
    content: [
      "Menumbuhkan empati lewat kebiasaan kecil. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Kehidupan sosial yang sehat ditopang oleh kepedulian, komunikasi sopan, dan kesediaan saling membantu.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "peduli-tetangga-saat-kesulitan",
    title: "Peduli Tetangga saat Kesulitan",
    excerpt: "Kepedulian praktis yang bisa dilakukan siapa saja.",
    category: "Sosial",
    date: "2026-08-04",
    readTime: "7 menit",
    cover: "/products/plan-50.jpg",
    coverAlt: "Ilustrasi koneksi multi perangkat",
    content: [
      "Kepedulian praktis yang bisa dilakukan siapa saja. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Kehidupan sosial yang sehat ditopang oleh kepedulian, komunikasi sopan, dan kesediaan saling membantu.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "hidup-rukun-di-lingkungan-padat",
    title: "Hidup Rukun di Lingkungan yang Padat",
    excerpt: "Menjaga kenyamanan saat rumah berdekatan.",
    category: "Sosial",
    date: "2026-08-03",
    readTime: "7 menit",
    cover: "/products/plan-voucher.jpg",
    coverAlt: "Ilustrasi voucher internet",
    content: [
      "Menjaga kenyamanan saat rumah berdekatan. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Kehidupan sosial yang sehat ditopang oleh kepedulian, komunikasi sopan, dan kesediaan saling membantu.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "etika-berkendara-di-kampung",
    title: "Etika Berkendara di Jalan Kampung",
    excerpt: "Keselamatan dan rasa hormat di jalan bersama.",
    category: "Sosial",
    date: "2026-08-02",
    readTime: "7 menit",
    cover: "/blog/blog-man-phone.jpg",
    coverAlt: "Pria memakai smartphone",
    content: [
      "Keselamatan dan rasa hormat di jalan bersama. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Kehidupan sosial yang sehat ditopang oleh kepedulian, komunikasi sopan, dan kesediaan saling membantu.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "menjaga-waktu-shalat-di-tengah-kesibukan",
    title: "Menjaga Waktu Shalat di Tengah Kesibukan",
    excerpt: "Ibadah tetap terjaga meski hari padat.",
    category: "Ibadah",
    date: "2026-08-01",
    readTime: "9 menit",
    cover: "/blog/blog-man-work.jpg",
    coverAlt: "Pria bekerja dengan laptop",
    content: [
      'Kesibukan kerja, sekolah, dan urusan rumah sering membuat waktu terasa mengejar. Padahal shalat adalah tiang yang menenangkan hati di tengah padatnya hari.',
      'Pasang pengingat yang jelas, tetapi jangan hanya mengandalkan alarm. Latih diri untuk segera bergerak ketika masuk waktu, bukan menunda berkali-kali.',
      'Siapkan ruang kecil yang bersih untuk shalat di rumah. Tempat yang rapi membantu hati lebih siap dan mengurangi alasan untuk menunda.',
      'Jika sedang bepergian, rencanakan jeda shalat sejak awal. Banyak keterlambatan terjadi karena jadwal disusun tanpa menyisakan ruang ibadah.',
      'Ajak keluarga saling mengingatkan dengan lembut. Pengingat yang penuh kasih lebih efektif daripada teguran kasar.',
      'Manfaatkan waktu singkat di antara aktivitas: wudu yang tertib dan shalat tepat waktu justru membantu menata ulang fokus.',
      "Jangan menunggu hari 'santai' untuk mulai konsisten. Konsistensi tumbuh dari keputusan kecil yang diulang tiap hari.",
      'Menjaga shalat bukan hanya kewajiban formal, tetapi cara merawat ketenangan. Hari yang diselingi ibadah biasanya terasa lebih tertata.',
    ],
  },
  {
    slug: "ibadah-yang-konsisten-meski-sederhana",
    title: "Ibadah yang Konsisten meski Sederhana",
    excerpt: "Amalan kecil rutin yang berdampak besar.",
    category: "Ibadah",
    date: "2026-07-31",
    readTime: "7 menit",
    cover: "/blog/blog-family.jpg",
    coverAlt: "Ayah dan anak belajar bersama",
    content: [
      "Amalan kecil rutin yang berdampak besar. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Ibadah yang terjaga memberi ketenangan. Mulai dari amalan yang sederhana namun konsisten setiap hari.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "menata-hati-sebelum-beraktivitas",
    title: "Menata Hati sebelum Beraktivitas",
    excerpt: "Awali hari dengan niat baik.",
    category: "Ibadah",
    date: "2026-07-30",
    readTime: "7 menit",
    cover: "/blog/blog-kids.jpg",
    coverAlt: "Anak-anak belajar bersama",
    content: [
      "Awali hari dengan niat baik. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Ibadah yang terjaga memberi ketenangan. Mulai dari amalan yang sederhana namun konsisten setiap hari.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "menghidupkan-malam-dengan-ibadah-ringan",
    title: "Menghidupkan Malam dengan Ibadah Ringan",
    excerpt: "Amalan malam realistis saat badan lelah.",
    category: "Ibadah",
    date: "2026-07-29",
    readTime: "7 menit",
    cover: "/blog/blog-elder.jpg",
    coverAlt: "Orang tua di rumah",
    content: [
      "Amalan malam realistis saat badan lelah. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Ibadah yang terjaga memberi ketenangan. Mulai dari amalan yang sederhana namun konsisten setiap hari.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "mensyukuri-nikmat-sehari-hari",
    title: "Mensyukuri Nikmat Sehari-hari",
    excerpt: "Melihat kebaikan kecil agar hidup lebih tenang.",
    category: "Ibadah",
    date: "2026-07-28",
    readTime: "9 menit",
    cover: "/blog/blog-elder-child.jpg",
    coverAlt: "Kakek dan cucu bersama",
    content: [
      'Syukur bukan hanya diucapkan saat mendapat hal besar. Latihan syukur paling kuat justru ada pada nikmat yang terlihat biasa: kesehatan, keluarga, dan kesempatan beraktivitas.',
      'Tiap malam, sebutkan tiga hal yang pantas disyukuri hari itu. Kebiasaan ini melatih hati untuk melihat yang ada, bukan hanya yang kurang.',
      'Syukur mendorong sikap hemat dan tidak boros. Orang yang merasa cukup biasanya lebih bijak mengelola rezeki.',
      'Ungkapkan terima kasih kepada orang di sekitar. Syukur sosial memperkuat hubungan dan mengurangi sikap merasa berhak atas segalanya.',
      'Dalam ibadah, syukur tampak dari konsistensi: menjaga shalat, berbagi, dan memakai waktu dengan baik.',
      'Tuliskan nikmat sederhana di buku catatan agar mudah diingat saat hari terasa berat.',
      'Ajarkan anak mengenali kebaikan kecil agar mereka tumbuh dengan hati yang lebih tenang.',
      'Dengan syukur yang hidup, hari-hari terasa lebih ringan. Bukan karena masalah hilang, tetapi karena hati punya ruang untuk melihat cahaya di antaranya.',
    ],
  },
  {
    slug: "manajemen-waktu-untuk-keluarga",
    title: "Manajemen Waktu untuk Keluarga Sibuk",
    excerpt: "Membagi kerja, istirahat, dan kebersamaan.",
    category: "Umum",
    date: "2026-07-27",
    readTime: "7 menit",
    cover: "/blog/blog-social.jpg",
    coverAlt: "Percakapan hangat di rumah",
    content: [
      "Membagi kerja, istirahat, dan kebersamaan. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Kebiasaan baik di rumah—dari waktu, kesehatan, sampai komunikasi—membentuk kualitas hidup jangka panjang.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "menjaga-kesehatan-mata-saat-online",
    title: "Menjaga Kesehatan Mata saat Lama di Layar",
    excerpt: "Kurangi mata lelah di era digital.",
    category: "Umum",
    date: "2026-07-26",
    readTime: "7 menit",
    cover: "/blog/blog-ibadah.jpg",
    coverAlt: "Suasana sudut ibadah di rumah",
    content: [
      "Kurangi mata lelah di era digital. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Kebiasaan baik di rumah—dari waktu, kesehatan, sampai komunikasi—membentuk kualitas hidup jangka panjang.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "menabung-sederhana-untuk-keluarga",
    title: "Menabung Sederhana untuk Keluarga",
    excerpt: "Kebiasaan keuangan ringan mulai bulan ini.",
    category: "Umum",
    date: "2026-07-25",
    readTime: "7 menit",
    cover: "/products/hero-impress.jpg",
    coverAlt: "Ilustrasi jaringan fiber optic",
    content: [
      "Kebiasaan keuangan ringan mulai bulan ini. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Kebiasaan baik di rumah—dari waktu, kesehatan, sampai komunikasi—membentuk kualitas hidup jangka panjang.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "mengurangi-sampah-di-rumah",
    title: "Mengurangi Sampah di Rumah Tangga",
    excerpt: "Jaga lingkungan mulai dari rumah.",
    category: "Umum",
    date: "2026-07-24",
    readTime: "7 menit",
    cover: "/products/plan-15.jpg",
    coverAlt: "Ilustrasi paket internet rumah",
    content: [
      "Jaga lingkungan mulai dari rumah. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Kebiasaan baik di rumah—dari waktu, kesehatan, sampai komunikasi—membentuk kualitas hidup jangka panjang.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
  {
    slug: "komunikasi-sehat-dalam-pernikahan",
    title: "Komunikasi Sehat dalam Pernikahan",
    excerpt: "Kebiasaan bicara yang merawat hubungan.",
    category: "Umum",
    date: "2026-07-23",
    readTime: "7 menit",
    cover: "/products/plan-30.jpg",
    coverAlt: "Ilustrasi aktivitas online rumah",
    content: [
      "Kebiasaan bicara yang merawat hubungan. Artikel ini membahas langkah praktis yang bisa langsung diterapkan di kehidupan sehari-hari.",
      "Kebiasaan baik di rumah—dari waktu, kesehatan, sampai komunikasi—membentuk kualitas hidup jangka panjang.",
      "Mulailah dari kesadaran bahwa perubahan kecil yang konsisten biasanya lebih kuat daripada niat besar yang cepat padam.",
      "Libatkan keluarga dalam kesepakatan agar aturan terasa adil dan mudah dijalankan bersama.",
      "Evaluasi hasil setelah satu hingga dua minggu, lalu sesuaikan kebiasaan yang masih memberatkan.",
      "Jangan ragu meminta saran kepada orang yang lebih berpengalaman, termasuk tetangga atau admin layanan terkait.",
      "Catat kemajuan sederhana agar motivasi tidak mudah hilang di tengah jalan.",
      "Yang terpenting adalah menjaga niat baik dan kebermanfaatan bagi diri sendiri serta orang di sekitar.",
    ],
  },
];

export function getPost(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug);
}

export function getLatestPosts(limit = 3): BlogPost[] {
  return [...blogPosts].sort((a, b) => b.date.localeCompare(a.date)).slice(0, limit);
}

export function formatBlogDate(date: string): string {
  return new Intl.DateTimeFormat("id-ID", { day: "numeric", month: "long", year: "numeric" }).format(new Date(date));
}

export const blogCategories: BlogCategory[] = [
  "WiFi & Internet",
  "Rumah Digital",
  "Teknologi",
  "Tips Hemat",
  "Adab",
  "Sosial",
  "Ibadah",
  "Umum",
];
